# Generated by Django 5.2.17 on 2026-08-27 15:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('URL', 'URL'), ('EMAIL', 'Email')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_level', models.CharField(blank=True, choices=[('VERY_LOW', 'Very Low'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='', max_length=12)),
                ('verdict', models.CharField(blank=True, default='', max_length=500)),
                ('rule_version', models.CharField(default='v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('analysis_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('scan_type__in', ['URL', 'EMAIL'])), name='scan_type_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'COMPLETED', 'FAILED'])), name='scan_status_valid'), models.CheckConstraint(condition=models.Q(('risk_level', ''), ('risk_level__in', ['VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL']), _connector='OR'), name='scan_risk_level_valid_or_empty'), models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 100)), _connector='OR'), name='scan_score_0_100_or_null')],
            },
        ),
        migrations.CreateModel(
            name='EmailScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, default='', max_length=320)),
                ('sender_domain', models.CharField(blank=True, default='', max_length=253)),
                ('reply_to', models.CharField(blank=True, default='', max_length=320)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body', models.TextField(blank=True, default='', max_length=30000)),
                ('attachment_names', models.TextField(blank=True, default='', max_length=2000)),
                ('raw_email', models.TextField(blank=True, default='', max_length=50000)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_scan', to='scans.scan')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('INFORMATIONAL', 'Informational'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=13)),
                ('points', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('evidence', models.TextField(blank=True, default='', max_length=1000)),
                ('explanation', models.TextField(max_length=2000)),
                ('recommendation', models.TextField(blank=True, default='', max_length=2000)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='scans.scan')),
            ],
            options={
                'ordering': ['sort_order', 'created_at', 'pk'],
                'indexes': [models.Index(fields=['scan', 'sort_order'], name='scans_indic_scan_id_b75bbc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('severity__in', ['INFORMATIONAL', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'])), name='indicator_severity_valid'), models.CheckConstraint(condition=models.Q(('points__gte', 0), ('points__lte', 100)), name='indicator_points_0_100')],
            },
        ),
        migrations.CreateModel(
            name='URLScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=2048)),
                ('normalized_url', models.CharField(blank=True, default='', max_length=2048)),
                ('scheme', models.CharField(blank=True, default='', max_length=32)),
                ('hostname', models.CharField(blank=True, default='', max_length=253)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('path', models.CharField(blank=True, default='', max_length=2048)),
                ('query', models.TextField(blank=True, default='', max_length=4096)),
                ('fragment', models.TextField(blank=True, default='', max_length=2048)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url_scan', to='scans.scan')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('port__isnull', True), models.Q(('port__gte', 1), ('port__lte', 65535)), _connector='OR'), name='url_scan_port_valid_or_null')],
            },
        ),
    ]
