# Generated by Django 5.2.17 on 2026-08-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailscan',
            name='attachment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailscan',
            name='extracted_url_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
